In [2]:
import numpy as np 
np.__version__

'1.26.4'

In [3]:
l_1d = list(range(1, 10))
l_1d

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
l_2d = []

for i in range(1, 11):
    l = list()
    for j in range(1,4):
        l.append(i**j)
    l_2d.append(l)

l_2d

[[1, 1, 1],
 [2, 4, 8],
 [3, 9, 27],
 [4, 16, 64],
 [5, 25, 125],
 [6, 36, 216],
 [7, 49, 343],
 [8, 64, 512],
 [9, 81, 729],
 [10, 100, 1000]]

In [5]:
l_1d = [[ i**j for i in range(4)] for j in range(10)]
l_1d

[[1, 1, 1, 1],
 [0, 1, 2, 3],
 [0, 1, 4, 9],
 [0, 1, 8, 27],
 [0, 1, 16, 81],
 [0, 1, 32, 243],
 [0, 1, 64, 729],
 [0, 1, 128, 2187],
 [0, 1, 256, 6561],
 [0, 1, 512, 19683]]

In [6]:
# Numpy vs List

In [7]:
arr = np.arange(20)
l = list(range(20))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
type(arr)

numpy.ndarray

In [9]:
import time

In [10]:
# %time for i in np.arange(200000000) : arr1 = arr*3

In [11]:
# %time for i in range(200000000) : arr1 = arr*3

In [12]:
l_1d = [1,2,3,4,5,6]
np_arr = np.array(l_1d)
np_arr

array([1, 2, 3, 4, 5, 6])

#Numpy Functions

In [13]:
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
arr.shape

(100,)

In [15]:
arr.ndim

1

In [16]:
arr.size

100

In [17]:
arr.dtype

dtype('int64')

In [18]:
float_arr =  arr.astype(np.float64)
float_arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [19]:
np.isnan(float_arr)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [20]:
float_arr[[2,5,6]] = np.nan
np.isnan(float_arr)

array([False, False,  True, False, False,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [21]:
only_num_arr = float_arr[~np.isnan(float_arr)]
only_num_arr.shape


(97,)

In [22]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [23]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [24]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [25]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [27]:
np.empty(5)

array([4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323, 2.5e-323])

In [28]:
arr_1d = np.arange(1,21)
arr_2d = arr_1d.reshape((5,4))
arr_2d.ndim

2

In [29]:
arr = np.arange(1,5)
arr * 2

array([2, 4, 6, 8])

In [30]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([4,7,6])

In [31]:
arr1.shape

(2, 3)

In [32]:
arr2.shape

(3,)

In [33]:
arr1 + arr2

array([[ 5,  9,  9],
       [ 8, 12, 12]])

In [34]:
arr1 - arr2

array([[-3, -5, -3],
       [ 0, -2,  0]])

In [35]:
arr1 * arr2

array([[ 4, 14, 18],
       [16, 35, 36]])

In [36]:
arr1 / arr2

array([[0.25      , 0.28571429, 0.5       ],
       [1.        , 0.71428571, 1.        ]])

In [37]:
arr = np.arange(1, 20)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [38]:
arr[4]

5

In [39]:
arr[1:5]

array([2, 3, 4, 5])

In [40]:
arr[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1])

In [41]:
arr[::-2]

array([19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [42]:
arr[::]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [43]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [44]:
arr[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [45]:
arr[:3]

array([1, 2, 3])

In [46]:
arr[-1]

19

In [47]:
arr[-2]

18

In [48]:
arr[1:8:2]

array([2, 4, 6, 8])

In [49]:
arr[1] = 10

In [50]:
arr

array([ 1, 10,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [51]:
arr_copy = arr[:].copy()
arr_copy

array([ 1, 10,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [52]:
arr_2d = np.arange(1,21).reshape(5,4)
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [53]:
arr_2d[1:3, 2:4]

array([[ 7,  8],
       [11, 12]])

In [54]:
arr_2d[:, 0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [55]:
arr_2d[0:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
arr_2d[3]

array([13, 14, 15, 16])

In [57]:
arr_2d[3,2]

15

In [58]:
arr_2d[:, 2]

array([ 3,  7, 11, 15, 19])

In [59]:
arr = np.arange(1, 11)
arr == 2

array([False,  True, False, False, False, False, False, False, False,
       False])

In [60]:
arr > 2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [61]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr_2d >4

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [63]:
arr_2d[arr_2d>4]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [64]:
a = np.arange(1, 4)
b = np.array([4, -5, 6])

In [65]:
np.dot(a,b)

12

In [66]:
a.dot(b)

12

In [67]:
a @ b

12

In [68]:
a = np.arange(1, 7).reshape(2,3)
b = np.array([[1,5], [1,-6], [4,9]])

In [69]:
b.shape

(3, 2)

In [70]:
a @ b

array([[15, 20],
       [33, 44]])

In [72]:
a = np.arange(1, 21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [73]:
a.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [75]:
np.arange(1,11).T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
a.max()

20

In [77]:
a.max(axis=1) 

array([ 5, 10, 15, 20])

In [78]:
a.max(axis=0) 

array([16, 17, 18, 19, 20])

In [79]:
a.min()

1

In [80]:
a.min(axis=1)

array([ 1,  6, 11, 16])

In [81]:
a.min(axis=0)

array([1, 2, 3, 4, 5])

In [83]:
a.sum()

210

In [84]:
a.sum(axis=1)

array([15, 40, 65, 90])

In [85]:
a.sum(axis=0)

array([34, 38, 42, 46, 50])

In [86]:
a.mean()

10.5

In [87]:
a.mean(axis=1)

array([ 3.,  8., 13., 18.])

In [88]:
a.mean(axis=0)

array([ 8.5,  9.5, 10.5, 11.5, 12.5])

In [91]:
arr = np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [99]:
arr_flatten =arr.flatten()

In [94]:
arr_ravel = arr.ravel()

In [97]:
arr_ravel[1]=100
arr_ravel

array([  1, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [98]:
arr

array([[  1, 100,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [101]:
arr_flatten[1] = 99
arr_flatten

array([ 1, 99,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
arr

array([[  1, 100,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [103]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9], [10,11,12]])

In [105]:
np.concatenate([a,b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [106]:
np.concatenate([a,b], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [107]:
np.concatenate([a,b], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [108]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [109]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])